nginx:
  build: ./nginx
  links:
      - api:api
  ports:
      - "80:80"
api:
  build: ./api
  ports:
      - "3001"
db:
  container_name: postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: "THE_USER"
    POSTGRES_PASSWORD: "THE_PASSWORD"
    POSTGRES_DB: "THE_DATABASE"
ghost:
  image: ghost
  ports:
    - "8080:2368"
  environment:
    NODE_ENV: "production"
  volumes:
    - ./ghost/content:/var/lib/ghost
  links:
    - db