nginx:
  build: ./nginx
  links:
    - api:api
    - elasticsearch:elasticsearch
    - ghost:ghost
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
api:
  build: ./api
  ports:
      - "8080:8080"
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch:/usr/share/elasticsearch/data
db:
  container_name: postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: "THE_USER"
    POSTGRES_PASSWORD: "THE_PASSWORD"
    POSTGRES_DB: "THE_DATABASE"
ghost:
  image: ghost
  ports:
    - "2368:2368"
  environment:
    NODE_ENV: "production"
  volumes:
    - ./ghost/content:/var/lib/ghost
  links:
    - db