api:
  build: ./api
  ports:
      - "8080:8080"
  links:
    - elasticsearch
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch:/usr/share/elasticsearch/data